#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

export LC_ALL=C.UTF-8

VENVDIR=/opt/ironic-python-agent
UPPER_CONSTRAINTS=/tmp/requirements/upper-constraints.txt
CHI_HW_MGR_DIR=/tmp/chi-hardware-manager

# install IPA inside the virtual environment
# $VENVDIR/bin/pip install -c $UPPER_CONSTRAINTS git+https://github.com/ChameleonCloud/chi-hardware-manager
$VENVDIR/bin/pip install -c $UPPER_CONSTRAINTS $CHI_HW_MGR_DIR
