on:
  push:
  workflow_dispatch:

jobs:
  build-builder:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build ipa agent
        run: |
          ./run_build.sh ${{ matrix.arch }}
      - name: upload built images
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: ipa-debian12-2023.1-chi-${{ matrix.arch }}
          compression-level: 0 # initramfs is already compressed
          if-no-files-found: error
          path: |
            output/ipa-debian12-2023.1-chi-${{ matrix.arch }}.d/dib-manifests/
            output/ipa-debian12-2023.1-chi-${{ matrix.arch }}.initramfs
            output/ipa-debian12-2023.1-chi-${{ matrix.arch }}.kernel
      - name: Output artifact info
        run:  echo 'Artifact info is ${{ steps.artifact-upload.outputs }}'
