on:
  push:

jobs:
  build-builder:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ipa_builder
          push: false
          load: true
          tags: ipa_builder:latest
      - name: build ipa agent
        run: |
          ./run_build.sh
      - name: upload built images
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: ipa-debian12-2023.1
          compression-level: 0 # initramfs is already compressed
          path: |
            output/ipa-debian12-2023.1.d/dib-manifests/
            output/ipa-debian12-2023.1.initramfs
            output/ipa-debian12-2023.1.kernel
      - name: Output artifact info
        run:  echo 'Artifact info is ${{ steps.artifact-upload.outputs }}'
